# render.yaml (Final Version for Render Free Tier)

databases:
  # 1. A PostgreSQL Database. This is the correct way to define it.
  - name: quiz-database
    plan: free

services:
  # 2. Your Flask Web Service
  - type: web
    name: flask-quiz-api
    env: python
    plan: free
    healthCheckPath: /api/health
    buildCommand: "pip install -r requirements.txt"
    # WORKAROUND: Combine migration and start command.
    # This runs 'flask db upgrade' every time your service starts.
    startCommand: "flask db upgrade && gunicorn manage:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quiz-database # Must match the database name above
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.13
      # Add your other secrets in the Render dashboard's Environment tab
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CORS_ORIGIN
        sync: false