"""Add QuizAttempt model and link to Submission

Revision ID: 35e6bf5a8ec4
Revises: 3acf55bc20c8
Create Date: 2025-09-06 05:44:54.868548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e6bf5a8ec4'
down_revision = '3acf55bc20c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quiz_id', name='_user_quiz_uc')
    )
    op.drop_table('test_case')
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.drop_column('graded_at')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_id', sa.Integer(), nullable=False))
                # --- FIX IS HERE ---
        # Give the foreign key a name, for example: 'fk_submission_quiz_attempt_attempt_id'
        batch_op.create_foreign_key(
            "fk_submission_quiz_attempt_attempt_id", 
            'quiz_attempt', 
            ['attempt_id'], 
            ['id']
        )
        # --- END OF FIX ---

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('attempt_id')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graded_at', sa.DATETIME(), nullable=True))

    op.create_table('test_case',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('input_data', sa.TEXT(), nullable=True),
    sa.Column('expected_output', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quiz_attempt')
    # ### end Alembic commands ###
