"""Add time_limit_minutes to Quiz model

Revision ID: a1c91a7beef1
Revises: 35e6bf5a8ec4
Create Date: 2025-09-06 05:52:52.029245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c91a7beef1'
down_revision = '35e6bf5a8ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('time_limit_minutes')

    # ### end Alembic commands ###
